//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentGoods
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string organization { get; set; }
        public string cityName { get; set; }
        public string countryName { get; set; }
        public string managerName { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
